{{- range $app := .Values.appGenerators }}
{{- if $app.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ $app.name }}
spec:
  {{- include "argo-app.template.spec" (dict "ArgoApp" $app) | nindent 2 }}
{{- end }}
{{- end }}
