{{- $template := (.Files.Get "files/list_template.yaml") | fromYaml }}
{{- range $appset := .Values.listGenerators }}
{{- if $appset.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ $appset.name }}
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/source/targetRevision
  generators:
    - list:
        elements:
          {{- $appset.apps | toYaml | nindent 10 }}
  template:
  {{- $appSpec := include "argo-app.template.spec" (dict "ArgoApp" $appset) | fromYaml }}
  {{- merge (dict "spec" $appSpec) $template | toYaml | nindent 4 }}
{{- end }}
{{- end }}
