{{- $template_name := (.Files.Get "files/list_template_name.yaml") }}
{{- range $appset := .Values.listGenerators }}
{{- if $appset.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ $appset.name }}
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/source/targetRevision
  generators:
    - list:
        elements:
          {{- $appset.apps | toYaml | nindent 10 }}
  template:
    metadata:
      {{- $template_name | nindent 6 }}
    spec:
      {{- include "argo-app.template.spec" (dict "ArgoApp" $appset) | nindent 6 }}
{{- end }}
{{- end }}
