{{- $template_name := .Files.Get "files/matrix_template_name.yaml" | trim -}}
{{- range $appset := .Values.matrixGenerators }}
{{- if $appset.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ $appset.name }}
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/source/targetRevision
  generators:
    - matrix:
        generators:
          - list:
              elements:
              {{- range $ns := $appset.namespaces }}
                - namespace: {{ $ns }}
              {{- end }}
          - list:
              elements:
                {{- $appset.apps | toYaml | nindent 16 }}
  template:
    metadata:
      {{- $template_name | nindent 6 }}
    spec:
      {{- include "argo-app.template.spec" (dict "ArgoApp" $appset) | nindent 6 }}
{{- end }}
{{- end }}
