{{- if eq "CronJob" .Values.appType -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  {{- with .Values.batch }}
  suspend: {{ default "false" .suspend }}
  schedule: {{ .schedule }}
  {{- end }}
  jobTemplate:
    spec:
      template:
        metadata:
        {{- include "app.pod.metadata" . | nindent 10 }}
        spec:
          restartPolicy: Never
        {{- include "app.pod.spec" . | nindent 10 }}
{{- end }}
