{{- if and .Values.istio.create .Values.istio.cluster.create }}
{{- $service := (include "app.fullname" . | trim) -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ $service }}-cluster
spec:
  hosts:
    - {{ $service }}
  http:
    - route:
    {{- include "app.istio.route.destination" (dict "RouteDest" (dict "host" $service)) | nindent 6 }}
{{- end }}
