{{- if eq "Rollout" .Values.appType -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- include "app.pod.metadata" . | nindent 6 }}
    spec:
    {{- include "app.pod.spec" . | nindent 6 }}
  strategy:
    {{- include "app.rollout.strategy" . | nindent 6 }}
{{- end }}
