{{- if .Values.argoproj.create -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argoproj.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  project: {{ .Values.argoproj.name }}
  source:
    repoURL: {{ .Values.argoproj.chartRepoURL }}
    targetRevision: {{ .Values.argoproj.targetRevision }}
    path: {{ .Values.argoproj.chartPath }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace.name }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=false
{{- end }}
