{{- if and .Values.namespace.create .Values.namespace.gateway.create -}}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.namespace.name }}
spec:
  gatewayClassName: {{ .Values.namespace.gateway.type }}
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
{{- end }}
