global:
  domain: argocd.ajeet.io
  namespaceOverride: argocd
  securityContext:
    runAsUser: 999
    runAsGroup: 999
    fsGroup: 999
  image:
    tag: "v2.14.11"
  logging:
    format: json
    level: warn

configs:
  params:
    server.insecure: true
    # -- Used if Argo CD is running behind reverse proxy under subpath different from /
    server.rootpath: ''
    # -- Directory path that contains additional static assets
    server.staticassets: /shared/app
    # -- Disable Argo CD RBAC for user authentication
    server.disable.auth: false
    reposerver.parallelism.limit: 10
  cm:
    admin.enabled: true
  rbac:
    policy.csv: "p, role:none, *, *, */*, deny\n\
      g, ajeet@github.com, role:admin\n\
      g, mar@github.com, role:readonly"
    policy.default: "role:none"
    scopes: "[groups, email]"
  secret:
    argocdServerAdminPassword: "$2y$10$kh.f4vXDkfBgBMaoKnASUuiV5uDLgo26bm8F7z0YgKY8NzE3DsTKu"
# https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/

## use Redis, do not use redis-ha due to resource usages
redis:
  enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

controller:
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  serviceAccount:
    create: true

server:
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  service:
    type: ClusterIP # LoadBalancer
  serviceAccount:
    create: true
  extensions:
    enabled: true
    extensionList:
      - name: rollout-extension
        env:
          - name: EXTENSION_URL
            value: https://github.com/argoproj-labs/rollout-extension/releases/download/v0.3.7/extension.tar

repoServer:
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

applicationSet:
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
