---
apiVersion: networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: aq-api-route
spec:
  parentRefs:
    - name: my-gateway
  hostnames:
    - "ajeet.io"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /argocd
      backendRefs:
        - name: argocd-web
          port:
            number: 8080
