# Where to deploy in Kubernetes
namespace:
  create: false
  name: dev-cpn
  gateway:
    create: true
    type: istio

argoproj:
  create: true
  name: myapp
  chartRepoURL: mydomain
  targetRevision: 1.0.0
  chartPath: helm-quarkus/
