{{- with .Values.gitRepoCred }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  url: {{ .url }}
  password: {{ .password }}
  username: {{ .username }}
{{- end }}
