{{- range $gitRepo := .Values.gitRepos }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $gitRepo.name }}
  labels:
    argocd.argoproj.io/secret-type: {{ default "repository" $gitRepo.secretType }}
stringData:
  type: {{ default "git" $gitRepo.type }}
  url: {{ $gitRepo.url }}
{{- end }}
