# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appGenerators:
  spark:
    enabled: true
    name: spark
    destination:
      server: https://kubernetes.default.svc
      namespace: middleware
    sources:
      - repoURL: registry-1.docker.io/bitnamicharts
        chart: spark
        targetRevision: 9.3.6
        helm:
          valueFiles:
            - $values/applications/spark/values.yaml
      - repoURL: https://github.com/ajeet476/argoproject.git
        targetRevision: HEAD
        ref: values
  istio-base:
    enabled: true
    name: istio-base
    destination:
      server: https://kubernetes.default.svc
      namespace: istio-system
    sources:
      - repoURL: https://istio-release.storage.googleapis.com/charts
        chart: base
        targetRevision: 1.25.2
        helm:
          valueFiles:
            - $values/applications/istio/base.yaml
      - repoURL: https://github.com/ajeet476/argoproject.git
        targetRevision: HEAD
        ref: values
  istio-istiod:
    enabled: true
    name: istio-istiod
    destination:
      server: https://kubernetes.default.svc
      namespace: istio-system
    sources:
      - repoURL: https://istio-release.storage.googleapis.com/charts
        chart: istiod
        targetRevision: 1.25.2
        helm:
          valueFiles:
            - $values/applications/istio/istiod.yaml
      - repoURL: https://github.com/ajeet476/argoproject.git
        targetRevision: HEAD
        ref: values
  istio-ingress:
    enabled: true
    name: istio-ingress
    destination:
      server: https://kubernetes.default.svc
      namespace: istio-public
    sources:
      - repoURL: https://istio-release.storage.googleapis.com/charts
        chart: gateway
        targetRevision: 1.25.2
        helm:
          valueFiles:
            - $values/applications/istio/ingress.yaml
      - repoURL: https://github.com/ajeet476/argoproject.git
        targetRevision: HEAD
        ref: values

listGenerators:
  prod-apps:
    enabled: true
    name: prod-apps
    destination:
      server: https://kubernetes.default.svc
      namespace: production
    source:
      repoURL: https://github.com/ajeet476/argoproject.git
      targetRevision: HEAD
      path: '{{.path}}'
      helm:
        valueFiles:
          - ../../applications/{{ .name }}/app_global.yaml
    apps:
      - name: cpn-api
        path: helm-charts/app
      - name: use-api
        path: helm-charts/app
  namespaces:
    enabled: true
    name: namespaces
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/ajeet476/argoproject.git
      targetRevision: HEAD
      path: helm-charts/namespace-common
      helm:
        valueFiles:
          - ../../applications/namespace/{{ .name }}.yaml
    apps:
      - name: dev
      - name: stg
      - name: prod
      - name: middleware
      - name: istio-system
      - name: istio-public

matrixGenerators:
  dev-apps:
    enabled: true
    name: dev-apps
    source:
      repoURL: https://github.com/ajeet476/argoproject.git
      targetRevision: HEAD
      path: '{{.path}}'
      helm:
        valueFiles:
          - ../../applications/{{ .name }}/app_global.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: '{{.namespace}}'
    namespaces:
      - dev
      - stg
    apps:
      - name: cpn-api
        path: helm-charts/app
      - name: use-api
        path: helm-charts/app
      - name: use-batch
        path: helm-charts/app
      - name: use-report
        path: helm-charts/app
      - name: demo-app
        path: helm-charts/app

gitRepoCred:
  enabled: false
  url: https://github.com/ajeet476
  username: ""
  password: ""

gitRepos:
  argoproject:
    enabled: false
    name: "argoproject"
    url: https://github.com/ajeet476/argoproject

projectGenerators:
  default:
    enabled: false
    name: default
