# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

listGenerators:
  - name: prod-apps
    repoURL: https://github.com/ajeet476/argoproject.git
    targetRevision: HEAD
    server: https://kubernetes.default.svc
    namespace: production
    apps:
      - name: cpn-api
        path: helm-charts/app
        helm:
          valueFiles:
            - applications/cpn-api/app_global.yaml
      - name: use-api
        path: helm-charts/app
        helm:
          valueFiles:
            - applications/use-api/app_global.yaml
  - name: namespaces
    repoURL: https://github.com/ajeet476/argoproject.git
    targetRevision: HEAD
    server: https://kubernetes.default.svc
    namespace: production
    apps:
      - name: dev-common
        path: helm-charts/namespace-common
        helm:
          valueFiles:
            - applications/namespace/dev.yaml
      - name: stg-common
        path: helm-charts/namespace-common
        helm:
          valueFiles:
            - applications/namespace/stg.yaml
      - name: prod-common
        path: helm-charts/namespace-common
        helm:
          valueFiles:
            - applications/namespace/prod.yaml

matrixGenerators:
  - name: dev-apps
    repoURL: https://github.com/ajeet476/argoproject.git
    targetRevision: HEAD
    server: https://kubernetes.default.svc
    namespaces:
      - dev
      - stg
    apps:
      - name: cpn-api
        path: helm-charts/app
        helm:
          valueFiles:
            - applications/cpn-api/app_global.yaml
      - name: use-api
        path: helm-charts/app
        helm:
          valueFiles:
            - applications/use-api/app_global.yaml
