# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

listGenerators:
  - name: prod-apps
    server: https://kubernetes.default.svc
    repoURL: https://github.com/ajeet476/argoproject.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - applications/{{ .name }}/app_global.yaml
    namespace: production
    apps:
      - name: cpn-api
        path: helm-charts/app
      - name: use-api
        path: helm-charts/app
  - name: namespaces
    server: https://kubernetes.default.svc
    repoURL: https://github.com/ajeet476/argoproject.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - applications/namespace/{{ .name }}.yaml
    apps:
      - name: dev
        path: helm-charts/namespace-common
      - name: stg
        path: helm-charts/namespace-common
      - name: prod
        path: helm-charts/namespace-common

matrixGenerators:
  - name: dev-apps
    repoURL: https://github.com/ajeet476/argoproject.git
    helm:
      valueFiles:
        - applications/{{ .name }}/app_global.yaml
    targetRevision: HEAD
    server: https://kubernetes.default.svc
    namespaces:
      - dev
      - stg
    apps:
      - name: cpn-api
        path: helm-charts/app
      - name: use-api
        path: helm-charts/app

gitRepoCred:
  url: https://github.com/ajeet476
  username: ""
  password: ""

gitRepos:
  - name: "argoproject"
    url: https://github.com/ajeet476/argoproject
